steps:

- id: "Executando testes unitários"
  name: 'gcr.io/cloud-builders/go:alpine'
  args: [ 'test', './github.com/kaissi/fct7-devops-ci-desafio', '-v' ]
  env: ['GOPATH=/go']

- id: "Executando o build para gerar imagem docker"
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '.'
    - '-t'
    - 'gcr.io/$PROJECT_ID/fct7-devops-ci-desafio:latest'
    
- id: "Testando a imagem gerada"
  name: 'gcr.io/$PROJECT_ID/fct7-devops-ci-desafio:latest'

images:
- 'gcr.io/$PROJECT_ID/fct7-devops-ci-desafio:latest'
